services:
  - type: web
    name: good-duck-web
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: ADMIN_SESSION_SECRET
        sync: false
      - key: DATA_DIR
        value: /data
      # DB settings
      - key: DB_PROVIDER
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: goodduck-postgres
          property: connectionString
      - key: DATABASE_INTERNAL_URL
        fromDatabase:
          name: goodduck-postgres
          property: connectionStringInternal
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: MAIL_TO
        sync: false
      - key: APP_BASE_URL
        value: https://goodduckweb.onrender.com
      # S3/R2 opcional
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_PUBLIC_BASE_URL
        sync: false
      - key: S3_FORCE_PATH_STYLE
        sync: false
    # disk:               # Si tu plan permite Disk, descomenta y ajusta
    #   name: data
    #   mountPath: /data
    #   sizeGB: 1

databases:
  - name: goodduck-postgres
    databaseName: goodduckdb
    user: goodduck
    plan: free
    region: oregon